image: maven:3.6.2-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn compile $MAVEN_OPTS

test:
  stage: test
  script:
    - mvn test $MAVEN_OPTS

deploy:
  stage: deploy
  script:
    - mvn install $MAVEN_OPTS
    - mv spigot/target/* spigot
    - mv bungee/target/* bungee
    - rm -rf spigot/target
    - rm -rf bungee/target
  only:
    - master
  artifacts:
    name: "DonatorJoin+"
    paths:
      - spigot/DonatorJoin+*.jar
      - bungee/DonatorJoin+*.jar