################################################################################################
#    ____                            _                        _           _                    #
#   |  _ \    ___    _ __     __ _  | |_    ___    _ __      | |   ___   (_)  _ __      _      #
#   | | | |  / _ \  | '_ \   / _` | | __|  / _ \  | '__|  _  | |  / _ \  | | | '_ \   _| |_    #
#   | |_| | | (_) | | | | | | (_| | | |_  | (_) | | |    | |_| | | (_) | | | | | | | |_   _|   #
#   |____/   \___/  |_| |_|  \__,_|  \__|  \___/  |_|     \___/   \___/  |_| |_| |_|   |_|     #
#                                                                                              #
################################################################################################

# Set to false to disable default MC join message.
joinmessage: false

# Set to false to disable default MC quit message.
quitmessage: false

# If true, only the highest priority rank will be broadcasted!
# If false, a broadcast for any found rank will be sent.
usepriorities: true

# If false, DonatorJoinPlus will use the 'name' you set in the ranks below as group identifiers.
# People with a group with the same name as the rank will get the join message.
#
# If true, DonatorJoinPlus will use the 'permission' you set in the ranks below as identifier.
# If the user has the permission it will send the highest priority join message,
# or all if usepriorities is set to false.
usepermissions: false

ranks:
  - name: 'VIP'
    permission: 'djp.vip'
    priority: 10
    join:
      enabled: true
      message: '&8(&cServer&8) &7(&aVIP&7) &b%player% &ehas joined the game!'
      sound:
        enabled: true
        sound: ENTITY_IRONGOLEM_DEATH
      firework: true
    quit:
      enabled: true
      message: '&8(&cServer&8) &7(&aVIP&7) &b%player% &ehas left the game!'
      sound:
        enabled: true
        sound: ENTITY_IRONGOLEM_DEATH
      firework: false
  - name: 'MVP'
    permission: 'djp.mvp'
    priority: 20
    join:
      enabled: true
      message: '&8(&cServer&8) &7(&9MVP&7) &b%player% &ehas joined the game!'
      sound:
        enabled: true
        sound: BLOCK_PORTAL_TRAVEL
      firework: true
    quit:
      enabled: true
      message: '&8(&cServer&8) &7(&9MVP&7) &b%player% &ehas left the game!'
      sound:
        enabled: true
        sound: BLOCK_PORTAL_TRAVEL
      firework: false