################################################################################################
#    ____                            _                        _           _                    #
#   |  _ \    ___    _ __     __ _  | |_    ___    _ __      | |   ___   (_)  _ __      _      #
#   | | | |  / _ \  | '_ \   / _` | | __|  / _ \  | '__|  _  | |  / _ \  | | | '_ \   _| |_    #
#   | |_| | | (_) | | | | | | (_| | | |_  | (_) | | |    | |_| | | (_) | | | | | | | |_   _|   #
#   |____/   \___/  |_| |_|  \__,_|  \__|  \___/  |_|     \___/   \___/  |_| |_| |_|   |_|     #
#                                                                                              #
################################################################################################

storage:
  # Possible storage types: FILE:JSON, FILE:YAML, MYSQL, SQLITE, H2. If using H2 or SQLITE, make sure to set max-pool-size to 1!
  type: 'FILE:JSON'

  # FILE only: when set to true, the data will be written to disk every time a toggle happens.
  # THIS CAN BE VERY INEFFICIENT, especially on larger servers.
  # When on false, file only gets saved when server shuts down (data can get lost with f.e. crashes)
  save-per-toggle: false

  # The hostname (IP) to connect to
  hostname: '127.0.0.1'
  # Port to be used
  port: 3306
  # The database / scheme name
  database: 'database'
  # The username, should at least have write & read access to the database above!
  username: 'username'
  # The password corresponding to the username above
  password: 'password'
  # Should DonatorJoinPlus try to establish a SSL connection? (only for SQL)
  useSSL: true

  pool:
    # How many connections are allowed to be made?
    # Find more information at:
    # https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
    # Pool sizing SHOULD BE SET TO 1 WHEN USING H2 OR SQLITE
    max-pool-size: 5
    # How many idle connections should be maintained?
    # It is recommended to set this to the same value as the max-pool-size
    min-idle: 5
    # Maximum lifetime of a connection. Time in seconds.
    max-lifetime: 1500
    # How long should DonatorJoinPlus wait before timing out a connection?
    connection-timeout: 8

# Set to false to disable default MC join message.
joinmessage: false

# Set to false to disable default MC quit message.
quitmessage: false

# If true, only the highest priority rank will be broadcasted!
# If false, a broadcast for any found rank will be sent.
usepriorities: true

# If false, DonatorJoinPlus will use the 'name' you set in the ranks below as group identifiers.
# People with a group with the same name as the rank will get the join message.
#
# If true, DonatorJoinPlus will use the 'permission' you set in the ranks below as identifier.
# If the user has the permission it will send the highest priority join message,
# or all if usepriorities is set to false.
usepermissions: false

messages:
  prefix: '&e&lDonatorJoin&b&l+ &7» '
  no-perm: '&cYou are not allowed to do this!'
  reloaded: '&aThe plugin has been reloaded successfully!'
  enabled: '&aJoin & quit messages are now enabled!'
  disabled: '&cJoin & quit messages are now disabled!'
  not-online: '&cThat player is not online!'

# Note that this will not work with most permission plugins, as they usually haven't loaded permissions yet
slotforcer:
  enabled: false

  # This in total would allow the maxplayers on a server to go up with 23 slots.
  # If your hosting service RESTRICTS the max players, then YOU SHOULD NOT USE THIS (as your server can be suspended)
  limits:
  # These are ADDITIONAL slots that can be allocated.
  # For example with maxplayers set to 20, then 5 extra people with a permission can join.
  - additional: 5
    permission: 'donatorjoin.limit.exceed.vip'
  - additional: 8
    permission: 'donatorjoin.limit.exceed.mvp'
  - additional: 10
    permission: 'donatorjoin.limit.exceed.staff'

ranks:
  - name: 'VIP'
    permission: 'djp.vip'
    priority: 10
    join:
      enabled: true
      message: '&8(&cServer&8) &7(&aVIP&7) &b%player% &ehas joined the game!'
      sound:
        enabled: true
        sound: ENTITY_IRONGOLEM_DEATH
      firework: true
    quit:
      enabled: true
      message: '&8(&cServer&8) &7(&aVIP&7) &b%player% &ehas left the game!'
      sound:
        enabled: true
        sound: ENTITY_IRONGOLEM_DEATH
      firework: false
    world:
      join:
        enabled: false
        message: '&8(&cServer&8) &7(&aVIP&7) &b%player% &ehas joined the world!'
        sound:
          enabled: true
          sound: ENTITY_IRONGOLEM_DEATH
        firework: true
      quit:
        enabled: false
        message: '&8(&cServer&8) &7(&aVIP&7) &b%player% &ehas left the world!'
        sound:
          enabled: true
          sound: ENTITY_IRONGOLEM_DEATH
        firework: false
  - name: 'MVP'
    permission: 'djp.mvp'
    priority: 20
    join:
      enabled: true
      message: '&8(&cServer&8) &7(&9MVP&7) &b%player% &ehas joined the game!'
      sound:
        enabled: true
        sound: BLOCK_PORTAL_TRAVEL
      firework: true
    quit:
      enabled: true
      message: '&8(&cServer&8) &7(&9MVP&7) &b%player% &ehas left the game!'
      sound:
        enabled: true
        sound: BLOCK_PORTAL_TRAVEL
      firework: false
    world:
      join:
        enabled: false
        message: '&8(&cServer&8) &7(&9MVP&7) &b%player% &ehas joined the world!'
        sound:
          enabled: true
          sound: BLOCK_PORTAL_TRAVEL
        firework: true
      quit:
        enabled: false
        message: '&8(&cServer&8) &7(&9MVP&7) &b%player% &ehas left the world!'
        sound:
          enabled: true
          sound: BLOCK_PORTAL_TRAVEL
        firework: false