name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - id: getspigotfilename
        run: echo "::set-output name=file::$(ls spigot/target/DonatorJoin+*.jar)"
      - name: Create artifact
        uses: actions/upload-artifact@v1
        with:
          name: DonatorJoin+ Spigot
          path: ${{ steps.getspigotfilename.outputs.file }}
      - id: getbungeefilename
        run: echo "::set-output name=file::$(ls bungee/target/DonatorJoin+*.jar)"
      - name: Create artifact
        uses: actions/upload-artifact@v1
        with:
          name: DonatorJoin+ BungeeCord
          path: ${{ steps.getbungeefilename.outputs.file }}
